### ISSUE TITLE
Benchmark with opcache

### ISSUE THREAD

**Issue by natebrunette** [tsantos84/serializer-benchmark#13]
I believe the results here are skewed because benchmarking is not taking advantage of opcaching. It would be nice if a server could be set up with opcache properly configured to see how these libraries will perform in production.

**Comment by tsantos84** [comment]
I don't think we need to setup the environment with a webserver and opcache enabled. The banchmarck makes a warmup to load all classes in memory and then start  the interactions to compute the mean time.  The warmup process will do exactly what the opcache does in this situation.

**Comment by natebrunette** [comment]
Phpbench states that it runs benchmarks in a separate process. I looked through the code, though, and I'm not sure that's the case. If it is in a separate process, I think the benchmarks would benefit from opcaching.

**Comment by tsantos84** [comment]
PhpBench runs the benchmarks in separate process and, again, I can't see the racional by enabling OPCache in php-cli applications. This would make sense if would need to benchmark the libraries on HTTP context, but is not the case here.

**Comment by natebrunette** [comment]
The reason you would want to support this is that a lot of the libraries rely on the opcache when loading caches from the filesystem.

**Comment by tsantos84** [comment]
I understand that in production environment the best practice is to use opcache, but the benchmark doesn't need the opcache enabled. Enabling opcache don't change the performance of libraries in this benchmark. Please, take a look at warmup process and you'll have an idea of I'm trying to explain.
